### PR TITLE
101 and 102 issue's solution

### PR DESCRIPTION
**Pull request by venkanna37**
Hi Darren, please check the 102 issue's solution function (process_info function). It can improve, I think.

### CODE REVIEW

**Comment by dkav** [comment]
Squash the commits so that there is just two – one for each fix. Also, remove all the formatting/linting changes – they make it  hard to discern the relevant modifications.

**Comment by dkav** [comment]
@venkanna37 I have updated the main repo and merged my changes back into it. Please create a new pull request with your commits there.

**Comment by venkanna37** [comment]
Thank you Darren. I will do that and let you know.

**Comment by dkav** [comment]
We could also reopen the closed pr (linkagescape/linkage-mapper/pull/137). It is up to you.

**Comment by venkanna37** [comment]
I thought of creating a feature branch from the main and send the pull
request. But now, IDK how automatic formattings happening in my editor. So,
let me check and send me the pull request.
this is the latest feature branch:
https://github.com/venkanna37/linkage-mapper/tree/main-log-feature

**Comment by venkanna37** [comment]
Or I can send the pull request from [this branch](https://github.com/venkanna37/linkage-mapper/tree/main-log-feature), so you can avoid formatting changes while merging.

**Pull request closed without merging**
